export const initialData = [
    {
        'nit-ci' : 4315360,
        'empresa_persona': 'Jeanethe Concepcion Corbalan Ayarza',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultor individual de linea : secretaria/o administrativa/o (CUCE:15-0006-00-771976-0-E)',
        'monto_contrato':32930,
        'fecha_sucripcion':'4-1-16',
        'fecha_resolucion':'11-3-16',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 1054037016 ,
        'empresa_persona': 'Sandoval Saldias Lourdes',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'servicio recurrente de alimentacion - gestion 2016 (segunda convocatoria) (CUCE:16-0006-00-611950-2-2)',
        'monto_contrato': 349440,
        'fecha_sucripcion': '19-2-16',
        'fecha_resolucion': '30-9-16',
        'causante_entidad': 'Contratista (Empresa)',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 4768461,
        'empresa_persona': 'Rosa Isela Quisbert Mamani',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultor individual de linea asistente de distribucion (CUCE:16-0006-00-662084-0-E)',
        'monto_contrato': 38850,
        'fecha_sucripcion':'2-6-16',
        'fecha_resolucion':'1-9-16',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 4889008,
        'empresa_persona': 'Jahel Paola Barrientos Goitia',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea: profesional juridico (CUCE:16-0006-00-672434-0-E)',
        'monto_contrato': 40875,
        'fecha_sucripcion':'18-7-16',
        'fecha_resolucion':'30-11-16',
        'causante_entidad':'Fuerza mayor o caso fortuito',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 4840128,
        'empresa_persona': 'Mariana Caussin Coronado',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de línea: profesional jurídico (CUCE:16-0006-00-684011-0-E)',
        'monto_contrato':32700,
        'fecha_sucripcion':'5-9-16',
        'fecha_resolucion':'16-12-16',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 2449448,
        'empresa_persona': 'Andres Huacani Yana',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea auxiliar de servicios - conductor gestión 2017 (CUCE:16-0006-00-725136-0-E)',
        'monto_contrato': 23148,
        'fecha_sucripcion':'3-1-17',
        'fecha_resolucion':'21-2-17',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 5967668,
        'empresa_persona': 'Nicolas Wilson Mujica Arias',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea: técnico administrativo - apoyo dirección general de asuntos administrativos (CUCE:16-0006-00-725142-0-E)',
        'monto_contrato': 47064,
        'fecha_sucripcion':'3-1-17',
        'fecha_resolucion':'6-10-17',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 4785226,
        'empresa_persona': 'Sandro Santos Velez Mamani',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea : profesional especialista jurídico-constitucional - gestión 2017 (CUCE:16-0006-00-725331-0-E)',
        'monto_contrato': 33210,
        'fecha_sucripcion':'27-6-17',
        'fecha_resolucion':'31-7-17',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 3355088,
        'empresa_persona': 'Milenka Betancourt Jorge De Souza',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea : editor(a) miultimedia - gestión 2017 (CUCE:16-0006-00-725654-0-E)',
        'monto_contrato': 43330,
        'fecha_sucripcion':'1-6-17',
        'fecha_resolucion':'30-6-17',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
    {
        'nit-ci' : 7010501,
        'empresa_persona': 'Gabriela Darma Ruiz Castillo',
        'entidad_contratante': 'Vicepresidencia Del Estado Plurinacional',
        'objeto_contratacion': 'consultoria individual de linea: profesional en sistematizacion de la informacion (CUCE:17-0006-00-728740-0-E)',
        'monto_contrato': 37714,
        'fecha_sucripcion':'9-1-17',
        'fecha_resolucion':'14-2-17',
        'causante_entidad':'Por acuerdo de partes',
        'causal': 'Otros',
    },
];